name: matrix_api_lite
description: Dead simple data model for the matrix.org client-server API.
version: 0.4.4
homepage: https://famedly.com
repository: https://gitlab.com/famedly/company/frontend/libraries/matrix_api_lite/
issues: https://gitlab.com/famedly/company/frontend/libraries/matrix_api_lite/-/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cbor: ^4.1.0
  coap:
    path: /home/sorunome/repos/famedly/frontend/coap
  http: ^0.13.0

dev_dependencies:
  build_runner: ^2.1.4
  pedantic: ^1.11.0
  test: ^1.14.4
